//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Customer")]

    public partial class Customer
    {
        public int CustomerId { get; set; }

        [Required]
        [StringLength(50)]
        [RegularExpression(@"^(?!.*([ ])\1)(?!.*([A-Za-z])\2{2})\w[a-zA-Z ]*$", ErrorMessage = "The valid Employee Name Should contains only alphabets and single character should not be repeated continuously for more than 2 time ")]
        public string CustomerName { get; set; }

        [Required]
        [StringLength(50)]
        public string CustomerMail { get; set; }


        [Required]
        [StringLength(10)]

        public string CustomerGender { get; set; }

        [Required]
        [StringLength(10)]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[6-9][0-9]{9}$", ErrorMessage = "The valid Mobile number should starts with between 6 and 9 and followed by 9 digit numbers")]

        public string CustomerPhoneNo { get; set; }

        [Required]
        [StringLength(100)]
        public string CustomerAddress { get; set; }
    }
}



