//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpMail { get; set; }
        public string Gender { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }

        [DataType(DataType.Date)]

        public System.DateTime DOJ { get; set; }
        public string Address { get; set; }
    }
}
