//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedId { get; set; }
        public string CustName { get; set; }
        public string CustMail { get; set; }
        public decimal CustPhone { get; set; }
        public string Custfeedback { get; set; }
    }
}
