//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Breed { get; set; }
        public string Age { get; set; }
        public string Description { get; set; }
        public string image { get; set; }
    }
}
