//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPet.Models
{


    public partial class User
    {
        public int Id { get; set; }



        public string User_Name { get; set; }



        public string User_Email { get; set; }



       
        public string PhoneNo { get; set; }



        public string Password { get; set; }



       
        public string Re_Password { get; set; }
    }
}
